### ISSUE TITLE
user-can-see-their-car.md

### ISSUE THREAD

**Issue by michael5522** [michael5522/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML skeleton

- [x] Make sure car is visible

- [x] Add CSS

- [x] Fix any problems
