### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by michael5522** [michael5522/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a simple data model that includes which way the car is facing.

- [x] Create an array with 4 items representing (north, south, east, or west).

- [x] Add event listener to listen for 'keydown' events on the document.

- [x] Add CSS to show the car position after 'keydown' is pressed.

- [x] Fix any errors.
