### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by michael5522** [michael5522/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to data model to hold the car's x and y coordinates on the page.

- [x] Use Absolute position

- [x] Use the style property of element objects to change your car's top and left box offset styles.

- [x] Space button event listener to move  16 milliseconds

- [x] Check for errors
