### ISSUE TITLE
User-can-stop-their-car

### ISSUE THREAD

**Issue by michael5522** [michael5522/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started.

- [x] When user clicks space car should start, when user click space again car should stop.

- [x] Check if everything is working correctly.
