### ISSUE TITLE
user can steer their car

### ISSUE THREAD

**Issue by michael5522** [michael5522/driving-game#9]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add the current vehicle direction into the object every time arrow key is pressed.

- [x] Change the vehicle style property depending on the orientation of the vehicle.

- [x] Move the car forward as usual
